### ISSUE TITLE
Security mode reject, cause 24, emm_sm.c:593

### ISSUE THREAD

**Issue by rphillips-quavant** [nextepc/nextepc#1]
Attempting to get an instance of NextEPC working to experiment with Ruckus Q910 & Q710 CBRS LTE small cells and the Essential PH-1 UE.  I am getting Security mode reject errors during the authentication, attached is a wireshark trace showing several failed attempts.  I have used the same eNodeB, UEs and SIM cards with another EPC from Ericsson and that configuration connects without issues.  

I'm using Gemalto SIM cards with the values:
K value: 77777777777777777777777777777777
OPc value: DB46EEF88A1A4F3BB05B1AD880DA07F2
AMF: 8000
IMSI: 543214000004020
MCC: 543
MNC: 214
MME_GID: 54321
MME_CODE: 5
TAC: 4

Any suggestions would be most appreciated.

[essential_phone_on_NextEPC.pcapng.zip](https://github.com/nextepc/nextepc/files/3179726/essential_phone_on_NextEPC.pcapng.zip)
[essential_phone_on_ericssonEPC.pcap.zip](https://github.com/nextepc/nextepc/files/3179727/essential_phone_on_ericssonEPC.pcap.zip)

**Comment by rphillips-quavant** [comment]
Should also mention i'm using the latest version of the source from this github account.

**Comment by nextepc** [comment]
We have a bug with 3-digit mnc. We will update the source codes on 20th May, and a release for Ubuntu will be done soon.

**Comment by rphillips-quavant** [comment]
thanks for the update - will update and test using the source once released and advise.

Cheers, Ron

**Comment by nextepc** [comment]
Please try again with the latest source code. Including these fixes, NextEPC v1.0.0 is also released for Ubuntu, and you can also install it using the Ubuntu package manager.

**Comment by rphillips-quavant** [comment]
Have retested using the latest source code and there is no change.  Attached is wireshark capture.  

Thanks, Ron
[capture5.pcap.zip](https://github.com/nextepc/nextepc/files/3204624/capture5.pcap.zip)

**Comment by nextepc** [comment]
As we see, there are only two differences comparing with Ericsson:
1. security algo: EIA2, EEA2 (ericsson)    EIA1, EEA0 (nextepc)
2. IMEISV request

First please try to change the configuration file of nextepc.
- open nextepc.conf in an editor
- search "security", and change the followings:
   integrity_order : [ EIA2 ]
   ciphering_order : [ EEA2 ]
And please attach pcap again after applying these. Thanks.

**Comment by rphillips-quavant** [comment]
Have made the updates to the security algo and rerun, capture attached.
[capture7.pcapng.zip](https://github.com/nextepc/nextepc/files/3205057/capture7.pcapng.zip)

**Comment by nextepc** [comment]
Then, #1 is not related. 

Do you have any other UE you can try to attach? What is the firmware version of the UE? 

Because we have the same UE, Essential PH-1, it is working fine in our lab. We don't have a Ruckus eNodeB. We can put IMEISV, but it should not be a problem since it is optional.

**Comment by rphillips-quavant** [comment]
Will look to see if another UE is available for testing.  The UE build number is PPR1.180610.091.

**Comment by nextepc** [comment]
We fixed this problem. Please retry it after updating the source code. 

https://github.com/nextepc/nextepc/commit/f9afbf24ccf64853c08c9f00e70fb90bfa1016ac

**Comment by rphillips-quavant** [comment]
Updated the source and no joy - capture attached.
[capture8.pcap.zip](https://github.com/nextepc/nextepc/files/3209742/capture8.pcap.zip)

**Comment by brandonjlee** [comment]
Sorry, we found more bugs on this issue. We didn't fully check yet, we will do tomorrow.
In the mean time, you may try it after updating the source code again.

**Comment by rphillips-quavant** [comment]
Tested about an hour ago with the latest code as of 5/23, 9:30 AM Eastern time and no change.  Did not have time to do a capture but will do so later today.  Also I have ordered new sim cards that using the 310 014 PLMN and can test using those if it helps.

**Comment by nextepc** [comment]
It seems that the problem comes from 3-digit MNC. We fixed a number of bugs around this, but it seems there are more. Therefore, it means that 310-014 may not work either. If you use 2-digit MNC sim cards (for example, 310-014 has 3-digit MNC, "014".) , that will work.  

Unfortunately we now have 2-digit MNC SIMs only, so we couldn't test our modification yet. Let us find a way to test it soon.

**Comment by rphillips-quavant** [comment]
I could provide you one of my SIMs if you like.  Could also provide remote access to my system for testing if you like.

**Comment by nextepc** [comment]
We've confirmed that our modification is correct, and now it works well with 3-digit mnc.
