### ISSUE TITLE
VoLTE Support

### ISSUE THREAD

**Issue by BorjanEch0** [nextepc/nextepc#13]
Hi!

I have managed to setup NextEPC core, Kamailio IMS (and connected them together in pcrf), 2 Test UEs and verified internet access via LTE on both with Internet APNs setup. kamailio with 2 users and made a test call via wifi and LTE using MizuDroid app.  My question now is:

What should i do next in order to support VoLTE in the sense of dialing the phone number via the build in phone app of the UEs and is it even possible.

Thank you!

**Comment by nextepc** [comment]
You need to program ISIM info into your SIM card which is used for VoLTE's SIP (IMS) procedure. We've not tested with IMS, you may consult this with your SIM card provider. 

In addition, you may need to set up additional "ims" APN with QCIs 1 & 5 in NextEPC.

**Comment by BorjanEch0** [comment]
I just found the VoLTE ISIM Section in my programming tool, i will let you know if it works, and if all is successful i can share how i did it. 
Thank you,

**Comment by r00tb3** [comment]
> I just found the VoLTE ISIM Section in my programming tool, i will let you know if it works, and if all is successful i can share how i did it.
> Thank you,

Any success with this?
