### ISSUE TITLE
Multiple EPC Nodes

### ISSUE THREAD

**Issue by infinitydon** [nextepc/nextepc#2]
Hi,

Does Nextepc support multiple deployments like having a pool scenario whereby you deploy more than one MME, SGW/PGW, PCRF? 

Is there a provision to use DNS for MME,SGW/PGW selection instead of hard-coding the IP addresses?

**Comment by nextepc** [comment]
Multiple instances can be used by setting multiple ip addresses and/or using "name".  For example, you can use the keyword "- name: sgw.mydomain.com", instead of "addr".

**Comment by infinitydon** [comment]
Thanks!
