### ISSUE TITLE
Integration external AAA and TWAG 

### ISSUE THREAD

**Issue by htechno** [nextepc/nextepc#24]
Hi there,
Is there any way to connect an external AAA RADIUS to DIAMETER converter to the HSS?
This is necessary to implement WiFi offload scheme via TWAG (Trusted WLAN Access Gateway - wifi controller that can build GTP in PGW)

Pavel

**Comment by nextepc** [comment]
You need to deploy a diameter interworking function. There is a business in this area, you can find some companies who have similar products. But we don't know any open source implementation is available.
