### ISSUE TITLE
Manual Camping of phones 

### ISSUE THREAD

**Issue by neilrep** [nextepc/nextepc#47]
Issue Description:
Manual camping of all brand of phones 

We're running an EPC --> enodeB --> SDR (b210) --> duplexer --> antenna . A complete set-up for a box base station. SRSENB 20.10.1 , UHD 3.15.0 

Expected Behavior :
All brands of Phones can camp to the network

Actual Behavior:

Not all phones can camp to the network automatically

(Phones that cannot camp) :
- Huwaei Y7a
- Xiaomi Redmi note 9 Pro

(Phones automatically camp either manual camping successful) :
- Realme C12
- Vivo Y15s

Also trying to exchange sims to each phones, and got a same scenario. When I tried to restart the phones (Huwaei & Xiaomi), both unable to connect the network

If you have any request of log files and other configuration files, please feel free to comment on this forum for me to get it posted. Thank you so much all for your future support.

[UE.s_Cannot_Latch.logs.txt](https://github.com/nextepc/nextepc/files/8105970/UE.s_Cannot_Latch.logs.txt)
[Phone_pcap_traces.zip](https://github.com/nextepc/nextepc/files/8105956/Phone_pcap_traces.zip)
extepc/nextepc/files/8105955/UE.s_Cannot_Latch.logs.txt)
[UE.s_Cannot_Latch.logs (1).txt](https://github.com/nextepc/nextepc/files/8106195/UE.s_Cannot_Latch.logs.1.txt)

**Comment by nextepc** [comment]
Hello,

It is a radio-layer issue. You should check this issue with your eNodeB stack running on the SDR.
