### ISSUE TITLE
Carrier Aggregation - RX channel 2 out of range for configured RX frontends

### ISSUE THREAD

**Issue by neilrep** [nextepc/nextepc#48]
Issue Description
Srsenb running error (LookupError: IndexError: multi_usrp: RX channel 2 out of range for configured RX frontends)

Setup Details
We're running an EPC --> enodeB --> SDR (b210) --> duplexer --> antenna . A complete set-up for a box base station. SRSENB 20.10.1 , UHD 3.15.0

Expected Behavior
No Error upon running srsenb

Actual Behaviour
After configuring and changing parameters for Carrier Aggregation using SDR Hardware, (link: https://docs.srslte.com/en/rfsoc/app_notes/source/2ca/source/index.html) As I run the srsenb, we facing UHD RF error.

see attached file of my configuration from rr.conf and enb.conf, I also attached the picture of srsenb error. See screen grab below.

![154192209-4e91cd04-b915-4c37-964b-e53b1dd00633](https://user-images.githubusercontent.com/98736497/154888564-bb245039-5f66-4483-9f60-f7a07f87db4d.png)
[enb.txt](https://github.com/nextepc/nextepc/files/8106162/enb.txt)
[rr.txt](https://github.com/nextepc/nextepc/files/8106164/rr.txt)

**Comment by nextepc** [comment]
Hello,

It is a radio-layer issue. You should check this issue with your eNodeB stack running on the SDR.
