### ISSUE TITLE
Clarification Needed

### ISSUE THREAD

**Issue by infinitydon** [nextepc/nextepc#5]
Hi,

Much thanks for your effort for this project, at least it gives me the opportunity to learn some of the intricacies in deploying an EPC (sorry I could not find a better name for the topic).

But I need some clarifications regarding the points below:

- HSS: I could not find information on how to configure the HSS in the MME configuration.. Also can the MME connect to multiple HSS? 

The HSS sample configuration does not have the option of configuring the listening IP address or interface.

- PCRF: The only information about this in the sample configuration is the following
```
parameter:

pcrf:
    freeDiameter: pcrf.conf
```
I could not find information on how to connect the PGW with the PCRF, also how do we configure policy rules for the PCRF?

- Can the SGW/PGW selection be dynamic (using DNS) instead of hard coding them inside the configuration files? Or is there a particular reason for using the current configuration style?

**Comment by nextepc** [comment]
You provide a web interface to manage information required by HSS and PCRF. 

See https://nextepc.org/installation

If you installed NextEPC from Ubuntu package manager, the web can be installed as follows:

sudo apt-get -y install curl
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
curl -sL https://nextepc.org/static/webui/install | sudo -E bash -


If you installed from the source code, the followings are needed to install the web: 

sudo apt-get -y install curl
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get -y install nodes
cd webui
npm install

Then, run it, and you can put user information for HSS and rules for PCRF.

**Comment by nextepc** [comment]
And, you can use the keyword "name" instead addr.
For example, "- name: sgw.mydomain.com" will initiate a DNS query with "sgw.mydomain.com".

**Comment by infinitydon** [comment]
How is the HSS configured inside the MME?

How is the PCRF configured inside the PGw?

**Comment by nextepc** [comment]
Diameter related configuration files are located in etc/nextepc/freeDiameter/*.conf. For instance, etc/nextepc/freeDiameter/mme.conf is defined by the mme configuration file (etc/mme.conf) as follows:

mme:
    freeDiameter: mme.conf
    ...

freeDiameter/*.conf file follows the format defined by freeDiameter, you may refer here: http://www.freediameter.net/trac/wiki/Configuration
 
By default, mme's ConnectPeer is defined by "hss.localdomain" to use the co-located HSS.

**Comment by infinitydon** [comment]
Much thanks for the explanation!

**Comment by infinitydon** [comment]
BTW, is there a way to test my installation without using a physical eNodeB or UE?

**Comment by nextepc** [comment]
In nextepc/test directory, you can run a test program to verify the installation. However, it will be depreciated, and we are working on a new method to test NextEPC.
