### ISSUE TITLE
MME Pooling or Multiple MME

### ISSUE THREAD

**Issue by NeilJohnR** [nextepc/nextepc#57]
We're running an Commercial EPC--> enodeB --> SDR (b210) --> duplexer --> antenna . A complete set-up for a box base station. SRSENB 21.10 ; UHD 3.15.0

Can we able to point enodeb (srsneb) to multiple mme or mme pooling? in order to try or test the scenarios for voicecalls and sms, if it is working on srs, what is our adjustment we need to do?

**Comment by nextepc** [comment]
Your enodeb should support s1-flex and needs to have multiple MME settings. We're not sure that srsEnb supports this.
We do support multiple MMEs with s1-flex.

Voice call and sms require other entities including IMS. Our latest open source which includes both 5G and LTE has an example for volte setup. Please refer this: https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/.
