### ISSUE TITLE
Roaming Handoffs using S6a/S8 

### ISSUE THREAD

**Issue by rphillips-quavant** [nextepc/nextepc#7]
I am looking to experiment with simulating handoffs between a home MME and a roaming partners HSS via the S6a/S8 interfaces.  I have two instances of nextepc up and running and looking to have my home MME contact the simulated roaming partners HSS for the authentication. Any guidance on if this can be supported and how to configure it.

**Comment by nextepc** [comment]
Hi Ronald,

I'm sorry that roaming is not supported in this version. Let me close this issue.
